### PR TITLE
fix compile warnings

### PR DESCRIPTION
**Pull request by abma**
this fixes most compile warnings with gcc / linux compile

### CODE REVIEW

**Comment by rlcevg** [comment]
Thanks!
Nice leak fixes.
How can i generate those warnings? It gives no warnings with default compiler parameters. Should i use Debug build type instead of RelWithDebInfo or something?

**Comment by abma** [comment]
what compiler are you using?

**Comment by rlcevg** [comment]
gcc (GCC) 5.2.0

**Comment by rlcevg** [comment]
Added -Wall in CMakeLists.txt and now it rains with warnings.
set(additionalCompileFlags "-DDEBUG_VIS -Wall")

**Pull request merged**
